services:
  mysql:
    image: mysql:latest
    container_name: mysql-container
    volumes:
      - db_data:/var/lib/mysql
    environment:
      - MYSQL_PASSWORD=1234
      - MYSQL_ROOT_PASSWORD=1234
      - MYSQL_DATABASE=db
    networks:
      - app-network

  backend:
    build:
      context: https://github.com/etec-integration-project/etec-pi-2024-backend-ElFonsi.git
      dockerfile: Computer_shop_backend/Dockerfile
    working_dir: /app/Computer_shop_backend
    environment:
      - MYSQLDB_HOST=mysql
      - MYSQLDB_PASSWORD=1234
      - MYSQLDB_DATABASE=db
      - MYSQLDB_USERNAME=root
      - MYSQLDB_DOCKER_PORT=3306
    depends_on:
      - mysql
    restart: always
    networks:
      - app-network

  frontend:
    build:
      context: https://github.com/etec-integration-project/etec-pi-2024-frontend-ElFonsi.git
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    restart: always
    networks:
      - app-network
    environment:
      - REACT_APP_BACKEND=
      
  nginx:
    build: 
      context: https://github.com/etec-integration-project/etec-pi-2024-backend-ElFonsi.git#main:nginx
      dockerfile: Dockerfile
    ports:
      - "80:80"
    depends_on:
      - frontend
      - backend
    networks:
      - app-network
  
volumes:
  db_data:

networks:
  app-network:
    driver: bridge
